spring:
  config:
    import: optional:file:../.env.development[.properties]

DB_URL: ${DB_URL}
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

REDIS_HOST: ${REDIS_HOST}
REDIS_PORT: ${REDIS_PORT}

MAIL_USERNAME: ${MAIL_USERNAME}
MAIL_PASSWORD: ${MAIL_PASSWORD}

FRONTEND_URL: ${FRONTEND_URL}

GOOGLE_CLIENTID: ${GOOGLE_CLIENTID}
GOOGLE_CLIENTSECRET: ${GOOGLE_CLIENTSECRET}

FACEBOOK_CLIENTID: ${FACEBOOK_CLIENTID}
FACEBOOK_CLIENTSECRET: ${FACEBOOK_CLIENTSECRET}

AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
AWS_SECRET_KEY: ${AWS_SECRET_KEY}
AWS_REGION: ${AWS_REGION}
AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}

IS_INITDB: false
IS_RUNDB_SCRIPT: never
